#!/bin/sh

echo "Triggering Telnetd " > /dev/ttyS0
/system/bin/busybox telnetd -l /system/bin/sh

echo "Triggering adbd " > /dev/ttyS0
mount -o rw,remount /
setprop services.adb.tcp.port 5555
/system/bin/adbd &

echo "Triggering SSH " > /dev/ttyS0
/system/bin/dropbear -d /usr/share/sshkeys/dropbear_dss_host_key -r /usr/share/sshkeys/dropbear_rsa_host_key -P /tmp/dropbear.pid 

echo "Triggering lighttpd " > /dev/ttySO
lighttpd -m /system/usr/lib -f /system/etc/httpd.conf

echo "Running Clear Crash Counter " > /dev/ttyS0
/system/bin/clear_crash_counter-orig

echo "Starting Eureka OTA Update Engine " > /dev/ttyS0
busybox sh /system/usr/share/eureka-apps/ota/chromecast-ota &

echo "Starting Whitelist-Sync Engine " > /dev/ttyS0
busybox sh /system/usr/share/eureka-apps/whitelist-sync/whitelist-sync &