#!/bin/sh

if busybox test $(EurekaSettings get Services telnet) = "1"; then
	echo "Triggering Telnetd " > /dev/ttyS0
	/system/bin/busybox telnetd -l /system/bin/sh
fi

if busybox test $(EurekaSettings get Services adb) = "1"; then
	echo "Triggering adbd " > /dev/ttyS0
	mount -o rw,remount /
	setprop services.adb.tcp.port 5555
	/system/bin/adbd &
fi

if busybox test $(EurekaSettings get Services ssh) = "1"; then
    if busybox test -f /data/flashcast/dropbear/dropbear_dss_host_key && busybox test -f /data/flashcast/dropbear/dropbear_rsa_host_key; then
	    echo "Triggering SSH " > /dev/ttyS0
	    /system/bin/dropbear -d /data/flashcast/dropbear/dropbear_dss_host_key -r /data/flashcast/dropbear/dropbear_rsa_host_key -P /tmp/dropbear.pid &
    else
        echo "SSH Keys Missing, Generating " > /dev/ttyS0
        busybox mkdir -p /data/flashcast/dropbear/
        /system/bin/dropbearkey -t rsa -f "/data/flashcast/dropbear/dropbear_rsa_host_key" > /dev/null 2>&1
        /system/bin/dropbearkey -t dss -f "/data/flashcast/dropbear/dropbear_dss_host_key" > /dev/null 2>&1
	    echo "Triggering SSH " > /dev/ttyS0
	    /system/bin/dropbear -d /data/flashcast/dropbear/dropbear_dss_host_key -r /data/flashcast/dropbear/dropbear_rsa_host_key -P /tmp/dropbear.pid &
    fi
fi

if ! busybox test -d "/data/eureka" ; then
	echo "Creating /data/eureka folder " > /dev/ttyS0
	mkdir /data/eureka
	busybox chmod -R 777 /data/eureka
else
	echo "Fixing /data/eureka permissions " > /dev/ttyS0
	busybox chmod -R 777 /data/eureka
fi

echo "Triggering lighttpd " > /dev/ttySO
lighttpd -m /system/usr/lib -f /system/etc/httpd.conf &

echo "Starting Eureka OTA Update Engine " > /dev/ttyS0
busybox sh /system/usr/share/eureka-apps/ota/chromecast-ota > /tmp/chromecast-ota.log &

echo "Clearing FTS Crash Counter " > /dev/ttyS0
sleep 45 && fts-set crashcounter.android 0 &

echo "Running SNTPD " > /dev/ttyS0
/bin/toolbox sntpd
