#!/bin/sh

echo "Triggering Telnetd " > /dev/ttyS0
/system/bin/busybox telnetd -l /system/bin/sh

echo "Triggering adbd " > /dev/ttyS0
mount -o rw,remount /
setprop services.adb.tcp.port 5555
/system/bin/adbd &

echo "Triggering SSH " > /dev/ttyS0
/system/bin/dropbear -d /usr/share/sshkeys/dropbear_dss_host_key -r /usr/share/sshkeys/dropbear_rsa_host_key -P /tmp/dropbear.pid 

echo "Triggering lighttpd " > /dev/ttySO
lighttpd -m /system/usr/lib -f /system/etc/httpd.conf

echo "Starting Eureka OTA Update Engine " > /dev/ttyS0
busybox sh /system/usr/share/eureka-apps/ota/chromecast-ota > /tmp/chromecast-ota.log &

echo "Clearing FTS Crash Counter " > /dev/ttyS0
sleep 45 && fts-set crashcounter.android 0 &

echo "Running SNTPD " > /dev/ttyS0
/bin/toolbox sntpd