#!/bin/sh

if busybox test $(EurekaSettings get Services telnet) = "1"; then
	echo "Triggering Telnetd " > /dev/ttyS0
	/system/bin/busybox telnetd -l /system/bin/sh
fi

if busybox test $(EurekaSettings get Services adb) = "1"; then
	echo "Triggering adbd " > /dev/ttyS0
	mount -o rw,remount /
	setprop services.adb.tcp.port 5555
	/system/bin/adbd &
fi

if busybox test $(EurekaSettings get Services ssh) = "1"; then
	echo "Triggering SSH " > /dev/ttyS0
	/system/bin/dropbear -d /usr/share/sshkeys/dropbear_dss_host_key -r /usr/share/sshkeys/dropbear_rsa_host_key -P /tmp/dropbear.pid &
fi

echo "Triggering lighttpd " > /dev/ttySO
lighttpd -m /system/usr/lib -f /system/etc/httpd.conf &

echo "Starting Eureka OTA Update Engine " > /dev/ttyS0
busybox sh /system/usr/share/eureka-apps/ota/chromecast-ota > /tmp/chromecast-ota.log &

echo "Clearing FTS Crash Counter " > /dev/ttyS0
sleep 45 && fts-set crashcounter.android 0 &

echo "Launching idlescreen application " > /dev/ttyS0
sleep 20 && curl -H "Content-Type: application/json" http://localhost:8008/apps/00000000-0000-0000-0000-000000000000 -X POST &

echo "Running SNTPD " > /dev/ttyS0
/bin/toolbox sntpd
