#!/bin/sh

echo "Triggering Telnetd " > /dev/ttyS0
/system/bin/busybox telnetd -l /system/bin/sh

echo "Triggering adbd " > /dev/ttyS0
mount -o rw,remount /
setprop services.adb.tcp.port 5555
/system/bin/adbd &

echo "Triggering SSH " > /dev/ttyS0
/system/bin/dropbear -d /usr/share/sshkeys/dropbear_dss_host_key -r /usr/share/sshkeys/dropbear_rsa_host_key -P /tmp/dropbear.pid 

echo "Running Clear Crash Counter " > /dev/ttyS0
/system/bin/clear_crash_counter-orig

echo "Starting PwnedCast Update Engine " > /dev/ttyS0
while true ; do busybox sh /chrome/pwnedcast-update.sh ; sleep 5 ; done